# Enable cronctl.
cronctl.enabled=true
# cronctl API path.
cronctl.api.default-path=/api/cronctl
# Use Spring-Security.
cronctl.security.enabled=false
# Enable swagger.
cronctl.swagger.enabled=true
# Enable unauthenticated access to swagger.
cronctl.swagger.public-access=true
# Swagger group.
cronctl.swagger.group=cronctl
# Swagger paths to match.
cronctl.swagger.paths-to-match=/api/cronctl