server:
  port: 8080

spring:
  application:
    name: sample-app

schedule:
  cron:
    job-a: 0 */5 * * * *

cronctl:
  security:
    enabled: false
  swagger:
    enabled: true
    public-access: true